server:
  port: 8080

spring:
  datasource:
    username: albert
    password: root
    url: jdbc:mysql://localhost:3306/ay-blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      # 解决swagger3和springboot版本冲突
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ay.ayblog.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.ay.ayblog: debug

springfox:
  documentation:
    swagger-ui:
      enabled: true